try {
    var x;
    x = 1;
    console.log(x);

    let x;
    x = 2;
    console.log(x);
} catch(error) {
    console.error(error);
}